language: java
jdk:
- openjdk14

before_install:
- sudo apt update
- sudo apt install openjfx

addons:
    sonarcloud:
        organization: "smarambas"
        token: "9d0cc22b670bba46342cb3cb8ccf8dc82843725a"
        
script: 
- ant build
- sonar-scanner
